### ISSUE TITLE
`alt` atribuut aan `img` geven

### ISSUE THREAD

**Issue by SamaraFellaDina** [itsValyria/the-startup-responsive-interactieve-website#3]
![image](https://github.com/itsValyria/the-startup-responsive-interactieve-website/assets/144009778/963be171-97de-426e-8a8b-db8ba05d5edf)

https://github.com/itsValyria/the-startup-responsive-interactieve-website/blob/6e5e3c44b0282234755baaca87b82df256100c89/index.html#L16

Je moet hier nog een `alt` element aan geven. 

![](https://media.giphy.com/media/2eK5gq7l3AX4zvLmlu/giphy.gif)

**Comment by itsValyria** [comment]
Yaaasss, dit probleem is inmiddels verholpen door een alt attribuut toe te voegen!

(sorry, dit was de enige die ik was vergeten, het spijt me, vergeef me)

**Comment by SamaraFellaDina** [comment]
kan echt niet hoor ;)

![](https://media.giphy.com/media/MoYC1N4nv7Fcs/giphy.gif)
