### ISSUE TITLE
Geen <akhi> attribuut op een <h2> element plaatsen

### ISSUE THREAD

**Issue by koeenm** [itsValyria/the-startup-responsive-interactieve-website#4]
<img src="https://github.com/itsValyria/the-startup-responsive-interactieve-website/assets/144009715/697f1e49-80e6-4f22-bade-6db8787aa91c">

https://github.com/itsValyria/the-startup-responsive-interactieve-website/blob/6e5e3c44b0282234755baaca87b82df256100c89/index.html#L35

Probeer geen < akhi > atribuut op een < h2 > te plaatsen.  Misschien kan je een data atribuut gebruiken ? 

(Akhi staat niet in de MDN html reference)

![](https://media.giphy.com/media/51FamSZ2pVYGs/giphy.gif)

**Comment by itsValyria** [comment]
Yaasss, dit probleem is verholpen door vak ''akhi'' ''data-akhi'' te maken! Woow!
